import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import { defineConfig, globalIgnores } from 'eslint/config';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    'node_modules/**',
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
  ]),
  {
    languageOptions: {
      globals: {
        NodeListOf: 'readonly',
        React: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
      '@typescript-eslint/consistent-type-imports': 'error',
      'react/self-closing-comp': 'error',
      'react/jsx-fragments': ['error', 'syntax'],
      'react/jsx-no-useless-fragment': ['error', { allowExpressions: true }],
      curly: 'error',
      'no-console': 'error',
      'capitalized-comments': [
        'error',
        'always',
        { ignoreConsecutiveComments: true },
      ],
      'spaced-comment': ['error', 'always'],
      'no-undef': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'no-const-assign': 'error',
      'one-var': ['error', 'never'],
      'no-multi-assign': 'error',
      'no-unused-vars': 'error',
      'no-new-object': 'error',
      'no-prototype-builtins': 'error',
      'prefer-object-spread': 'error',
      'object-shorthand': 'error',
      'no-array-constructor': 'error',
      'prefer-template': 'error',
      'no-eval': 'error',
      'no-useless-escape': 'error',
      'func-names': ['error', 'as-needed'],
      'wrap-iife': ['error', 'outside'],
      'no-loop-func': 'error',
      'prefer-rest-params': 'error',
      'default-param-last': 'error',
      'no-new-func': 'error',
      'no-param-reassign': 'error',
      'prefer-spread': 'error',
      'prefer-arrow-callback': 'error',
      'arrow-body-style': ['error', 'as-needed'],
      'no-confusing-arrow': 'error',
      'no-unreachable': 'error',
      'no-useless-constructor': 'error',
      'no-dupe-class-members': 'error',
      'class-methods-use-this': 'error',
      'no-duplicate-imports': 'error',
      'no-iterator': 'error',
      'dot-notation': 'error',
      'prefer-exponentiation-operator': 'error',
      'no-plusplus': 'error',
      'no-template-curly-in-string': 'error',
      'no-use-before-define': 'error',
      eqeqeq: ['error', 'always'],
      'no-nested-ternary': 'error',
      'no-else-return': ['error', { allowElseIf: false }],
      'no-new-wrappers': 'error',
      'id-length': 'error',
      'new-cap': 'error',
      'no-underscore-dangle': 'error',
      'prefer-destructuring': ['error', { array: false, object: true }],
      'import/no-anonymous-default-export': 'off',
    },
  },
]);

export default eslintConfig;
